### ISSUE TITLE
Administrate and Delete Mitsubishi Accounts  

### ISSUE THREAD

**Issue by Gemuir** [jeatheak/Mitsubishi-WF-RAC-Integration#110]
The Mitsubishi Accounts sensor shows the number of accounts (in my case 4) but there is no way to view them and or delete one or more of them. This would be a great feature to have,

**Comment by jeatheak** [comment]
Hi, This is not possible because only the registered account can delete itself.
So if you delete the airco in homeassistant the integrations sends a delete command to the airco. Only this account will then be deleted.

So if you have 4 accounts it means that 4 different devices (homeassistant, smart-m air apps) are registered. (4 is the max).
To delete 1 or more accounts you need the de-register the airco in for example the smart-m air app.

If there are old connections that residde from deleted apps or integrations there is no way of deleting the accounts other than factory reset the wifi module. (you need to physicaly press the reset button on the module).

**Comment by Matthew1471** [comment]
If unit has WiFi built in then physical press is not required.. can be done from the remote.

For example for SRK20ZSX-WF,-WFB,-WFT, SRK25ZSX-WF,-WFB,-WFT, SRK35ZSX-WF,-WFB,-WFT,
SRK50ZSX-WF,-WFB,-WFT, SRK60ZSX-WF,-WFB,-WFT you can look at the manual https://www.mhi-mth.co.jp/en/products/detail/air-conditioner_users_manual.html#RAC_RLF012A216B Page 33 entitled "Initialization of wireless LAN interface" and for the setup of the WiFi again https://www.mhi-mth.co.jp/en/products/detail/air-conditioner_users_manual.html#SmartMAir

**Comment by jeatheak** [comment]
Ow Thanks! 😁 I did not know that. I will try to add some instructions for this.
