### ISSUE TITLE
Can't add device

### ISSUE THREAD

**Issue by mariusnauj** [jeatheak/Mitsubishi-WF-RAC-Integration#26]
Hello,

I used this integration time before, now my HA discovered device but i can't add it. I got error without any explanation.

**Comment by jeatheak** [comment]
Hi @mariusnauj,

Ow that it weird. We did have it one time earlier and then it was caused by a duplicate IP I think. Have you tried adding it manually?

**Comment by mariusnauj** [comment]
Yes, I tried add it manualy, but the same. I pinging this wf-rac IP from HA it respons. I do not do anythink, but after 10min I can add it without errors. I don't know why, but sometimes it drops connection. Inside and outside temperatures stuck, and need restart HA.

**Comment by jeatheak** [comment]
Ok, when your Airco is not responding this a known issue (see #15 and #9).
A few minutes ago I did make a new release if you do use Hacs than there should be a update.
This update has some general fixes and also some connection improvements. Maybe this will help.

Otherwise restarting HA is for now the only solution. Till we find the fix for #15 and #9

**Comment by mariusnauj** [comment]
Ok, thank you
