### ISSUE TITLE
Add humidity sensor 

### ISSUE THREAD

**Issue by SanderKo85** [jeatheak/Mitsubishi-WF-RAC-Integration#32]
Hi!

My units does have Humidity sensors on the unitboard.
In the tech manual I found them, but only for some model series.
(In my case the SRK25ZS-W indoor, SCM40ZS-W outdoor)

How can I/we find out how to get the value?
Thank you!

Sander.

**Comment by kababoom** [comment]
Does the app support this sensor?

**Comment by SanderKo85** [comment]
Not that I see, but the app (Smart M-Air) is as outdated as f***, missing more than only this...

**Comment by jeatheak** [comment]
Hey,

The app is indeed outdated. but the problem is that we only have the information the app provides.
At the moment it is very difficult to determine what to read and send without the code of the app. (the values are encrypted)

So for know I think it would to difficult to implement the humidity sensor.

**Comment by kababoom** [comment]
Exactly, that's why I asked about the app.

Is there any way you now have access to the humidity value?

**Comment by SanderKo85** [comment]
hmm, I really don't know how at this point.

**Comment by jeatheak** [comment]
Close for now because the app still has no Humidity sensor in it.
