### ISSUE TITLE
Transform the project to IOBroker

### ISSUE THREAD

**Issue by wolkeSoftware** [jeatheak/Mitsubishi-WF-RAC-Integration#35]
Hello jeatheak,
sorry for contacting you via the issue-tracker, but I'm really stuck with the integration of the WF-RAC into ioBroker and maybe you can help with some hints? 
I made an adapter for ioBroker on the base of your code and the original java-code of the app. The communication is working fine, as far as i can say, i get the data from the aircon. But it is not possible to send data. I've integrated the function to register the adapter to the airco via updateAccountInfo, the number of the connected devices (numOfAccount) is correct (but the array of the remoteList shows 4 empty strings although I think, this is correct). Every time, I send the data via setAirconStat I get no errors, except the result-code is set to 2. 
Is there anything, you can help me with? Maybe I have to use a special Operator-ID or Device-ID? Here is a link to my repo on github, maybe you find some obvious mistake: [https://github.com/wolkeSoftware/ioBroker.woso_mitsu_aircon_rac](https://github.com/wolkeSoftware/ioBroker.woso_mitsu_aircon_rac)

**Comment by jeatheak** [comment]
Hey not problem contacting this way.

Good to hear that the connections seems to work. For sending I also got some problems in the beginning. 

The remote list should/can be empty because it will only contain the operator IDs that are created/generated that are connecting to their remote app service. 
The local operator IDs are not shown.

It is indeed necessary to use the updateAcountInfo to register the operator id at the airco. Otherwise it won't accept the command. 

What is the account number? Because it can only have a maximum of 4 devices registered. If you don't know the operator IDs anymore you can only factory reset the device to clear the devices.

Have you tried sending a known command? I did sniff some traffic using a proxy and send that payload to know if it even would accept my commands/payload from the code.

**Comment by wolkeSoftware** [comment]
Thank you for the information. 
Can you send me a command with some explanation of how the settings would change, so I can try it - or which kind of proxy do you use to catch the commands from the app?
I've fixed some issues in the last week, but none of them changed the problems on sending data. I've tested the crc, which is fine, I've tested the bytecode, which should be fine too. So the only thing that I can't check is the sending itself and the updateAccountInfo, because none of them returning any error-code. 
Thanx in advance for your help, Mike

**Comment by wolkeSoftware** [comment]
thanks again for your support - I've installed a proxy to find out, what the correct code to send would have to look like and found out, that my transformation to base64 - the very last step to create the command - had a larger bug in it. I've fixed it now and so the adapter for iobroker should work right now.
Mike

**Comment by jeatheak** [comment]
ok nice to hear
