### ISSUE TITLE
Climate: Set fan mode Auto

### ISSUE THREAD

**Issue by NJansDev** [jeatheak/Mitsubishi-WF-RAC-Integration#51]
Hello,

I am trying to implement the airco within an automation and am unable to set the airco to automatic fan mode with the Service call "Climate: Set fan mode". Modes 1 to 5 do work. As far as I had looked into the code, and it might be as simple as to add a translation in the const.py:
`FAN_AUTO = "0 Auto"`?

Kind regards,
Noud

**Comment by jeatheak** [comment]
Hi @NJansDev,

To get the FAN_AUTO working you need to use "auto" instead of "0 auto"
You can lookup the supported modes in de Developers->states tab

![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/50164603/9b49d876-d22a-45bf-978e-768f33f9e225)

And test it with the service call tab

![image](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/50164603/6c07675c-c73b-4aa2-b479-d02feb7b76c2)

This worked for me.
If you have any other questions let me know.

**Comment by NJansDev** [comment]
> Hi @NJansDev,
> 
> To get the FAN_AUTO working you need to use "auto" instead of "0 auto" You can lookup the supported modes in de Developers->states tab
> 
> ![image](https://user-images.githubusercontent.com/50164603/247021907-9b49d876-d22a-45bf-978e-768f33f9e225.png)
> 
> And test it with the service call tab
> 
> ![image](https://user-images.githubusercontent.com/50164603/247021988-6c07675c-c73b-4aa2-b479-d02feb7b76c2.png)
> 
> This worked for me. If you have any other questions let me know.

I am a bit ashamed that I didn't know this before...
Thanks for the solution!
