### ISSUE TITLE
Add energy sensor

### ISSUE THREAD

**Issue by jeatheak** [jeatheak/Mitsubishi-WF-RAC-Integration#6]
Some Airco models have built in energy monitoring.
It is possible to read this and add is as an energy senor

**Comment by jeatheak** [comment]
It is implemented with release v0.1.0 and PR #11 
But there can be some issues so I will not close this one yet

**Comment by virtualdj** [comment]
How do you interpret the energy monitoring sensor?
These days I had the Airco always turned off and the app reports 13.5 kWh (as it actually counts the total kWh of the month), while HA has a value variable in time but negative (-35.25 kWh usually).

Today:

![immagine](https://user-images.githubusercontent.com/3251704/184397925-1b617f3e-0a41-40b8-991a-3fbaec68db63.png)

Previous days including today (it has always been off, so I would expect a straight line):

![immagine](https://user-images.githubusercontent.com/3251704/184398009-07a6718a-7a6f-4b5f-b75b-a5698488fb6c.png)

Is it working correctly in your case? Or maybe you don't have a model with the energy sensor?

**Comment by jeatheak** [comment]
Hey,

At the moment I don't calculate the energy usage. The value that is returned from te parsed airco payload is converted into a sensor. 

I did add the sensor to the energy dasboard and on my side it looks like it is working.

But till now I did not find the correct way to implement it from the app code. I will try to investigate what is happing here.

**Comment by virtualdj** [comment]
So you don't get negative values? I mean on the sensor directly, just like the screenshots above, and **not** in the energy dashboard.

**Comment by KixAss** [comment]
It looks like it’s working on my end. I don’t get negative values. 

What you could do to add a power-usage sensor is to substract the previous value from the current value (and devide by 1000 to get Watt). You’ll need to check if the value is higher, else it could be reset and you’ll need to return 0.

**Comment by virtualdj** [comment]
> I will try to investigate what is happing here.

With some help I was able to debug the application and I managed to capture these strings:
```
AACnmbL/AAAAAAASCgAAAAAAAf////8RCYAEABE0qQAAiAAAAgAAAAAAABWAIKn/gBC//4EgbP+BEP7/ghBG/4cQbf+FEA7/sRAA/5AQAP+UEBcAHyD//x8Q//8TEPoAERAA/w0A//8hEP//MhoE/zQRAQQ1EAP/HhAA/x4RAf9fIA==

AACnmbL/AAAAAAASCgAAAAAAAf////8RCYAEABE0qQAAiAAAAgAAAAAAABWAIKn/gBDA/4EgbP+BEP7/ghBG/4cQbf+FEA7/sRAA/5AQAP+UEBcAHyD//x8Q//8TEPoAERAA/w0A//8hEP//MhoE/zQRAQQ1EAP/HhAA/x4RAf8GPw==
```
all of them should result in a `ac.Eletric = 5.75` according to the app debugging; the app itself then shows 13.5 kWh because it probably sums this value with previous from the cloud? Anyway, **no negative values here**.

So, I took your code from commit 7adae44, because I don't know how to run it "manually" on Python with the recent commits that have the Home Assistant integration (is it possible, and if so, how?).

I changed your **main.py** like this:
```python
import json
from src.parser import Parser
from src.models.aircon import Aircon
from src.repository.repository import Repository
from src.utils import Utils
from base64 import b64decode

# My decoding test (first of the base64 strings above)
statusString = 'AACnmbL/AAAAAAASCgAAAAAAAf////8RCYAEABE0qQAAiAAAAgAAAAAAABWAIKn/gBC//4EgbP+BEP7/ghBG/4cQbf+FEA7/sRAA/5AQAP+UEBcAHyD//x8Q//8TEPoAERAA/w0A//8hEP//MhoE/zQRAQQ1EAP/HhAA/x4RAf9fIA=='
ac = Parser.translateBytes(statusString)
currentStatus = json.dumps(ac.__dict__, sort_keys=False, indent=4)
print(currentStatus)
```
Running this "static decoding" results in:
```json
{
    "Operation": false,
    "PresetTemp": 26.0,
    "OperationMode": 0,
    "AirFlow": 2,
    "WindDirectionUD": 2,
    "WindDirectionLR": 3,
    "Entrust": false,
    "CoolHotJudge": false,
    "ModelNr": 0,
    "Vacant": 0,
    "ErrorCode": "00",
    "IndoorTemp": 27.5,
    "OutdoorTemp": 25.0,
    "Electric": -37.0
}
```
As you can see on the last line, **there's the negative value**. I also placed a breakpoint [here](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/7adae44029d25cf1e5c89523744d8704c7a08bd3/python/src/parser.py#L219) and compared the values of all the 130 bytes of the `content` variable with the ones captured from the debugging: they're **exactly the same**.

So probably there's something wrong in the [decoding function](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/7adae44029d25cf1e5c89523744d8704c7a08bd3/python/src/parser.py#L246) or the previous byte packing? Unfortunately I'm not able to debug the single steps of the calculation in the app... I only know the starting point (the base64 string) and the final result (i.e. the value of the *Electric* field). Could this be of any help?

**Comment by KixAss** [comment]
One other weird thing: the bottom airco hasn’t been on, but has the same usage as the airco above that one. 

![86BE3B0C-760C-473C-B6E4-77815070C0ED](https://user-images.githubusercontent.com/5183112/184479309-b8a1a410-aa76-4c78-824f-e26086dd1aca.jpeg)

**Comment by virtualdj** [comment]
To get the `5.75` these two lines:
https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/4454fdd94918e1b745e0af601f6145fcd5e2f8b2/custom_components/mitsubishi-wf-rac/wfrac/rac_parser.py#L269-L270
must be changed to:
```python
 if len(value_segment) >= 39: 
     ac_device.Electric = ((value_segment[39] << 8) + value_segment[38]) * 0.25 
```
![immagine](https://user-images.githubusercontent.com/3251704/184494471-a6ef5ead-d0fc-437e-8d49-175de620e11a.png)

**Comment by virtualdj** [comment]
@jeatheak I would also check this:
https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/4454fdd94918e1b745e0af601f6145fcd5e2f8b2/custom_components/mitsubishi-wf-rac/wfrac/rac_parser.py#L266-L268
`value_segment[n]` should be a byte; when it is negative all is working well, but what happens when it goes positive? I think a `IndexError: list index out of range` error.

Probably it's better to replace the whole block like this (avoiding checking the length, too?):
```Python
ac.Electric = None
for i in range(0, len(valueSegment), 4):
    if (valueSegment[i] == -128 and valueSegment[i+1] == 32):
	ac.IndoorTemp = (Constants.indoorTemp[valueSegment[i+2] & 0xFF])
    if (valueSegment[i] == -128 and valueSegment[i+1] == 16):
	ac.OutdoorTemp = (Constants.outdoorTemp[valueSegment[i+2] & 0xFF])
    if (valueSegment[i] == -108 and valueSegment[i+1] == 16):
	ac.Electric = (((valueSegment[i+3] << 8) + valueSegment[i+2]) * 0.25)
```

**Comment by mcheijink** [comment]
I think that this check is done because not all units report back their energy usage. 
And it can probably be optimized a bit, since the current implementation is logically a copy of the official android app’s implementation.
And the official implementation contains some weird stuff…
After my holidays (in 1.5 week) I can have a thorough look at it.

**Comment by jeatheak** [comment]
Hi Guys,

Thank you for all the investigations I did not have much time on hand. But I did push a new fix on the main branch.
I did find that the parsed values for energy can be different per airco.

So I added a while loop that loops trough the last segment. and checks if a combination of bytes are pressent.

If you guys could test it for me that would be awesome. If all is correct I will make a new Release.

**Comment by virtualdj** [comment]
> I did find that the parsed values for energy can be different per airco.

Thanks. As you can see, now the energy value is stable and doesn't change like on my chart on the previous posts. It seems that we're OK now (though it's still different from what the app reports)!

![immagine](https://user-images.githubusercontent.com/3251704/184640013-530d1259-741b-4549-8d35-d554f8bb0740.png)

> Thanks @virtualdj

We're here to help each other, that's the good thing of the open source and Github!

> Today, the airco reported 0 kWh. So it seems to be resetting to zero every day.

In my case, it doesn't reset every day. In fact it's still `5.75` now, and the airco has not been switched on in the meanwhile.

**Comment by KixAss** [comment]
When I look at my stats, it's like it is being reset every time i turn the airco off and on:

![image](https://user-images.githubusercontent.com/5183112/184640755-ab5ff4ce-83c5-4f00-b560-d5877a2fd11c.png)

(i'm still using the old v0.1.0)

**Comment by jeatheak** [comment]
Ok good to hear.

> In my case, it doesn't reset every day. In fact it's still 5.75 now, and the airco has not been switched on in the meanwhile.

The reset only happens when you switch on the airco.
So if you don't use the airco it will keep those values. (but I'm not entirely sure, I did see that happening once)

>(though it's still different from what the app reports)!
The app has more data. it concats the data from the entire month

**Comment by KixAss** [comment]
Maybe it would be nice to add a sensor where you calculate the power-usage (in Watt instead of kWh). Then you'll have the current usage and can calulate anything you want (for example with the Utility-integration).

If i'm correct you can calculate kWh to Watt when you get the Current kWh - Previous kWh (delta_kWh). Then you calculate the Current timestamp - Previous timestamp (in seconds) (delta_s).

Then you can calculate Watt by: (delta_kWh / delta_s) * 1000 * 3600

**Comment by mcheijink** [comment]
> Maybe it would be nice to add a sensor where you calculate the power-usage (in Watt instead of kWh). Then you'll have the current usage and can calulate anything you want (for example with the Utility-integration).
> 
> If i'm correct you can calculate kWh to Watt when you get the Current kWh - Previous kWh (delta_kWh). Then you calculate the Current timestamp - Previous timestamp (in seconds) (delta_s).
> 
> Then you can calculate Watt by: (delta_kWh / delta_s) * 1000 * 3600

I would not be in favor of this, since we are doing work on the data reported by the airco. And this is easily implemented by creating a “derivative” sensor of the energy usage.

**Comment by jeatheak** [comment]
I will leave this open for a few days to check if everything is going ok.
Please let me know if it working correctly.

**Comment by mcheijink** [comment]
![image](https://user-images.githubusercontent.com/10964320/186946554-65c2d14c-cc88-484e-a7bf-2e5aa0dc4f69.png)
It seems to roll back when it hits 32 kWh, which is a quarter of 128. 
The step size is 0.25 kWh. This would indicate that we are using 8 bit to display the energy usage, and that Python perhaps needs to interpret the data as an unsigned integer instead of a signed integer.
8 bit still seems low for this type of data. Especially since we are reading the data from two bytes. So perhaps it would be beter to interpret it as a uint16 (or int16)?

**Comment by virtualdj** [comment]
> The step size is 0.25 kWh. This would indicate that we are using 8 bit to display the energy usage, and that Python perhaps needs to interpret the data as an unsigned integer instead of a signed integer.
> 8 bit still seems low for this type of data. Especially since we are reading the data from two bytes. So perhaps it would be beter to interpret it as a uint16 (or int16)?

I don't know how Python works, but in the the app, that uses Java, the calculation is done like so:
```java
int high_part;
byte low_part;
double result = ((double)(((high_part & 0xFF) << 8) + (low_part & 0xFF))) * 0.25;
```
AFAIK both `int` and `byte` in Java should be signed, but the `high_part` is in a bitwise AND that should remove the sign as it's dropping the most significant byte. The `low_part` could be signed, though.

So considering the maximum `high_part` and `low_part` we have: (255 * 256 [left shift of 8 bits] + 127) * 0.25 = (65280 + 127) * 0.25 = 1635175 kWh which should be more than enough... Provided that the bytes are coming in correctly, of course.

This is the current Python code:
https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/10cb10434ca36c27d6ab4b596b474be964c17f87/custom_components/mitsubishi-wf-rac/wfrac/rac_parser.py#L269-L270

I think you're right, because as bytes in Java are always signed, the first part of the Python:
```Python
(vals[i + 3] << 8)       # TODO: vals[i + 3] must always be positive!
```
is not a correct translation. Previously, there's a function that converts the bytes to signed (to look like Java I presume):
https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/blob/10cb10434ca36c27d6ab4b596b474be964c17f87/custom_components/mitsubishi-wf-rac/wfrac/rac_parser.py#L222-L225
but this is not correct for the part above and should be changed to return an always positive number (0..255).
How to do that in Python is out of my knowledge :-(
