### ISSUE TITLE
Add scheduling interface

### ISSUE THREAD

**Issue by mkoegel** [jeatheak/Mitsubishi-WF-RAC-Integration#63]
Hi,

it would be great to be able to also scheduling for the on/off times of the A/C via Homeassistant.
Is this possible?

The UI in the App is really bad.

**Comment by stunBock** [comment]
When adding scheduling, is it possible to set the hvac mode to heat only within the sceduling UI? 

Background: 
When using the App for scheduling, the airco always starts in automatic mode. Meaning that if targettemp is lower then the actual temperature (wich is often the case, because the thing heats +5 degrees over targettemp before pausing)
The airco starts to use my precious electric Energy to COOL DOWN THE ROOM IN THE MIDLE OF THE WINTER! It drives me crazy!

**Comment by mkoegel** [comment]
@stunBock I use the weekly scheduling in the Smart M-Air app which allows you to also set the mode. 
I would hope this is available via API as well.

**Comment by stunBock** [comment]
Oh! I didnt see that function. Thanks for replying. That Helps a lot allready

**Comment by jeatheak** [comment]
for now im not going to implement this. you can create this using the schedule helper togerther with an automation
