### ISSUE TITLE
Onboarding error

### ISSUE THREAD

**Issue by henneonrails** [jeatheak/Mitsubishi-WF-RAC-Integration#91]
my experience with this integration is:

<img width="580" alt="Bildschirmfoto 2024-03-26 um 16 41 02" src="https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/123651/8abdce13-7280-4b03-a2e0-ce1b8f4406ea">

can someone help with it?

Thank you 

regards
Holger

**Comment by goprojojo** [comment]
Looks like hou need to deregister your device:
https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/issues/81

**Comment by jeatheak** [comment]
How many devices are connected through the smart m air app? 

See options in the airco menu and then at the bottom of the page.

![Screenshot_2024-04-14-14-42-01-52_384370620dd12cc50d79844845f8e7ae.jpg](https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/50164603/fa355a00-560c-4037-81d2-94adb8d05841)

**Comment by henneonrails** [comment]
Not one device is connect through the m air app. I use airconwithme if i would like to address the ac(s). But that‘s not true either. At the moment I use a homekit gateway called homebridge. With a module which connects via http or api direct in my home network to the mhi ACs. I could also call the ACs with http request and i could also control them via http if I like. So I wonder why I cannot do this with a more popular network like this here.

**Comment by jeatheak** [comment]
Are you sure the airco you are using has a Mitsubishi WF-RAC wifi module inside the airco?

Because that's the only module that works with this integration. 

Any other would have another communication protocol.

As far as I know the only way to serve commands to the airco is with the smart m air app. Because they use encryption. Normal http commands cannot work with this module.

If you can send commands to the airco using normal http requests or other platforms such as home bridge you should look for an integration that does the same. This integration only works with WF-RAC modules.

**Comment by henneonrails** [comment]
oh yes thank you for the clearance.

My wifi module is a intesis? Strange that there are multiple solutions for the one problem. 

<img width="1291" alt="Bildschirmfoto 2024-04-15 um 08 37 20" src="https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/assets/123651/febf8d30-4959-44c7-9ddb-a1cf23460634">

I think this will be the right one for me:

> Home Assistant IntesisBox Climate Platform
> 
> This platform allows Home Assistant to control IntesisBox devices https://www.intesisbox.com/en/wifi/gateways/ using the WMP protocol.
> 
> Unlike IntesisHome, IntesisBox allows for control through the local network via TCP sockets which is better suited for using with home automation platforms.
> 
> This has only been tested with a device emulator to the specifications, please report any issues or create a pull request.
>
